-- DROP TABLE IF EXISTS account;

-- SELECT *
-- FROM account;

-- CREATE TABLE IF NOT EXISTS public.account
-- (
--     account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
--     account_firstname character varying NOT NULL,
--     account_lastname character varying NOT NULL,
--     account_email character varying NOT NULL,
--     account_password character varying NOT NULL,
--     account_type account_type NOT NULL DEFAULT 'Client'::account_type,
--     CONSTRAINT account_pkey PRIMARY KEY (account_id)
-- );

SELECT *
FROM account;

--Query 1 Insert the row below
INSERT INTO account
(account_firstname, account_lastname, account_email, account_password)
VALUES ( 'Tony', 'Stark', 'tony@starkent.com', 'Iam1ronM@n');

SELECT *
FROM account;


--Query 2 Update the account type for the account table from 'Client' to 'Admin'
UPDATE account
SET account_type = 'Admin'
WHERE account_id = 1;


SELECT *
FROM account;

--Query 3 Delete the row identified as account_id '1' from the account table.
DELETE FROM account
WHERE account_id = 1;

SELECT *
FROM inventory;


-- REPLACE(column, from_text, to_text);

-- UPDATE inventory
-- SET inv_description = REPLACE(inv_description, 'a huge interior', 'small interiors')
-- WHERE inv_make = 'GM' AND inv_model = 'Hummer';

--Query 4 update the inv-description text from 'small interiors' to 'a huge interior'.
UPDATE inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

SELECT *
FROM inventory;



--Query 5  Inner joing to view inv-make, inv_model and classification_name of inventory items 
--that belong to "Sport" category.
SELECT inv.inv_make AS make, inv.inv_model AS model, clas.classification_name AS classification
FROM inventory inv INNER JOIN classification clas
ON inv.classification_id = clas.classification_id
WHERE clas.classification_name = 'Sport';


-- UPDATE inventory
-- SET inv_image = REPLACE(inv_image, '/images/vehicles', '/images'),
-- 	inv_thumbnail = REPLACE(inv_thumbnail, '/images/vehicles', '/images');


--Query 6 Changing path from '/images' to '/images/vehicles'
SELECT *
FROM inventory;

UPDATE inventory
SET inv_image = REPLACE(inv_image, '/images', '/images/vehicles'),
	inv_thumbnail = REPLACE(inv_thumbnail, '/images', '/images/vehicles');
	
SELECT *
FROM inventory;

